### PR TITLE
fix: improve session handling and normalize pokemon counter. 

### LINKED ISSUE #97: DefaultPokemon setting is not applied when using Windsurf
I'm experiencing an issue where the vscode-pokemon.defaultPokemon setting is not being applied.

Even after following the documented steps to reset the session, the default Pokémon are not loaded.

I'm using Windsurf (VS Code fork) instead of standard VS Code, so this may be related.

### PR DESCRIPTION
**Pull request by kasp470f**
This pull request refactors how the Pokémon collection is initialized and persisted across sessions, and improves the robustness of the Pokémon counter logic. The changes introduce helper functions for managing session state, streamline the code for spawning Pokémon, and ensure the Pokémon counter is always valid, preventing negative or undefined values.

This should also resolve #97 

**Panel Initialization Improvements:**
- Changed panel initialization to start with an empty session if there is no recoverable Pokémon state, rather than spawning a default Pokémon, making session behavior more predictable and avoiding unintended Pokémon spawns.

These changes improve code maintainability, reduce duplication, and ensure consistent, predictable behavior for Pokémon collection and counter state across sessions.

### CODE REVIEW

File: src/panel/main.ts [hunk 1]
```diff
@@ -319,10 +327,10 @@ function removePokemonFromPanel(
 
       pokeballEl.remove();
 
-      // 🔥 maintenant seulement on modifie l'état
+      // 🔥 now only modify the state
```
Comment (kasp470f) [inline src/panel/main.ts]: Not sure if this is the right translation, just asked AI to translate.

Comment (KevOneRedOne) [reply src/panel/main.ts]: @kasp470f if you want the right translation french to english 
'only now we change the state'

**Review by jakobhoeg — APPROVED** [review]
